# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delivery_ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delivery_ui_window(object):
    def setupUi(self, delivery_ui_window):
        delivery_ui_window.setObjectName("delivery_ui_window")
        delivery_ui_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(delivery_ui_window)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 143, 121, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 415, 161, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(470, 80, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(470, 310, 261, 231))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.delivery = QtWidgets.QPushButton(self.centralwidget)
        self.delivery.setGeometry(QtCore.QRect(300, 74, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.delivery.setFont(font)
        self.delivery.setObjectName("delivery")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 19, 151, 41))
        font = QtGui.QFont()
        font.setFamily("新蒂下午茶体")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.seeWareHouseInventory = QtWidgets.QPushButton(self.centralwidget)
        self.seeWareHouseInventory.setGeometry(QtCore.QRect(280, 139, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeWareHouseInventory.setFont(font)
        self.seeWareHouseInventory.setObjectName("seeWareHouseInventory")
        self.seeContainerInventory = QtWidgets.QPushButton(self.centralwidget)
        self.seeContainerInventory.setGeometry(QtCore.QRect(280, 409, 151, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeContainerInventory.setFont(font)
        self.seeContainerInventory.setObjectName("seeContainerInventory")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(430, 147, 41, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(430, 416, 41, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(220, 147, 61, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(230, 416, 51, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(160, 200, 171, 161))
        self.graphicsView.setObjectName("graphicsView")
        delivery_ui_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(delivery_ui_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        delivery_ui_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(delivery_ui_window)
        self.statusbar.setObjectName("statusbar")
        delivery_ui_window.setStatusBar(self.statusbar)

        self.retranslateUi(delivery_ui_window)
        QtCore.QMetaObject.connectSlotsByName(delivery_ui_window)

    def retranslateUi(self, delivery_ui_window):
        _translate = QtCore.QCoreApplication.translate
        delivery_ui_window.setWindowTitle(_translate("delivery_ui_window", "配送员子界面"))
        self.comboBox.setItemText(0, _translate("delivery_ui_window", "请选择仓库"))
        self.comboBox_2.setItemText(0, _translate("delivery_ui_window", "请选择货柜"))
        self.delivery.setText(_translate("delivery_ui_window", "配送"))
        self.label.setText(_translate("delivery_ui_window", "欢迎配送员"))
        self.seeWareHouseInventory.setText(_translate("delivery_ui_window", "查看仓库存量"))
        self.seeContainerInventory.setText(_translate("delivery_ui_window", "查看货柜存量"))
