# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finance_ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finance_ui_window(object):
    def setupUi(self, finance_ui_window):
        finance_ui_window.setObjectName("finance_ui_window")
        finance_ui_window.resize(800, 678)
        self.centralwidget = QtWidgets.QWidget(finance_ui_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("新蒂下午茶体")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.seeContainerMonthSales = QtWidgets.QPushButton(self.centralwidget)
        self.seeContainerMonthSales.setGeometry(QtCore.QRect(230, 88, 181, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeContainerMonthSales.setFont(font)
        self.seeContainerMonthSales.setObjectName("seeContainerMonthSales")
        self.seeContainerSales = QtWidgets.QPushButton(self.centralwidget)
        self.seeContainerSales.setGeometry(QtCore.QRect(230, 206, 211, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeContainerSales.setFont(font)
        self.seeContainerSales.setObjectName("seeContainerSales")
        self.seeGoodSales = QtWidgets.QPushButton(self.centralwidget)
        self.seeGoodSales.setGeometry(QtCore.QRect(230, 144, 211, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeGoodSales.setFont(font)
        self.seeGoodSales.setObjectName("seeGoodSales")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 246, 161, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(460, 68, 311, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(410, 98, 51, 20))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        self.line.setBaseSize(QtCore.QSize(0, 0))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(440, 154, 21, 16))
        self.line_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_2.setBaseSize(QtCore.QSize(0, 0))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(440, 216, 21, 16))
        self.line_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_3.setBaseSize(QtCore.QSize(0, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.seeContainerGoodSales = QtWidgets.QPushButton(self.centralwidget)
        self.seeContainerGoodSales.setGeometry(QtCore.QRect(230, 268, 211, 40))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeContainerGoodSales.setFont(font)
        self.seeContainerGoodSales.setObjectName("seeContainerGoodSales")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(440, 278, 21, 16))
        self.line_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_4.setBaseSize(QtCore.QSize(0, 0))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(200, 216, 31, 20))
        self.line_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_5.setBaseSize(QtCore.QSize(0, 0))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(183, 226, 40, 61))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(200, 278, 31, 20))
        self.line_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_7.setBaseSize(QtCore.QSize(0, 0))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(170, 246, 31, 20))
        self.line_8.setSizeIncrement(QtCore.QSize(0, 0))
        self.line_8.setBaseSize(QtCore.QSize(0, 0))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(410, 330, 361, 301))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 450, 61, 31))
        font = QtGui.QFont()
        font.setFamily("新蒂下午茶体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(60, 370, 211, 191))
        self.graphicsView_2.setObjectName("graphicsView_2")
        finance_ui_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(finance_ui_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        finance_ui_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(finance_ui_window)
        self.statusbar.setObjectName("statusbar")
        finance_ui_window.setStatusBar(self.statusbar)

        self.retranslateUi(finance_ui_window)
        QtCore.QMetaObject.connectSlotsByName(finance_ui_window)

    def retranslateUi(self, finance_ui_window):
        _translate = QtCore.QCoreApplication.translate
        finance_ui_window.setWindowTitle(_translate("finance_ui_window", "财务员子界面"))
        self.label.setText(_translate("finance_ui_window", "欢迎财务员"))
        self.seeContainerMonthSales.setText(_translate("finance_ui_window", "按月份查看销售额"))
        self.seeContainerSales.setText(_translate("finance_ui_window", "查看指定货柜的销售额"))
        self.seeGoodSales.setText(_translate("finance_ui_window", "查看每种商品的销售额"))
        self.comboBox.setItemText(0, _translate("finance_ui_window", "(请选择货柜)"))
        self.seeContainerGoodSales.setText(_translate("finance_ui_window", "查看货柜的商品销售额"))
        self.label_2.setText(_translate("finance_ui_window", "可视化"))
