# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stock_ui_window(object):
    def setupUi(self, stock_ui_window):
        stock_ui_window.setObjectName("stock_ui_window")
        stock_ui_window.resize(797, 681)
        self.centralwidget = QtWidgets.QWidget(stock_ui_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 231, 61))
        font = QtGui.QFont()
        font.setFamily("新蒂下午茶体")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(123, 172, 141, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.seeWareHouseInventory = QtWidgets.QPushButton(self.centralwidget)
        self.seeWareHouseInventory.setGeometry(QtCore.QRect(283, 165, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.seeWareHouseInventory.setFont(font)
        self.seeWareHouseInventory.setObjectName("seeWareHouseInventory")
        self.stock = QtWidgets.QPushButton(self.centralwidget)
        self.stock.setGeometry(QtCore.QRect(283, 79, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.stock.setFont(font)
        self.stock.setObjectName("stock")
        self.addGood = QtWidgets.QPushButton(self.centralwidget)
        self.addGood.setGeometry(QtCore.QRect(283, 121, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.addGood.setFont(font)
        self.addGood.setObjectName("addGood")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(428, 88, 331, 131))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(413, 175, 16, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(263, 175, 21, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 278, 161, 22))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.seeContainerInventory = QtWidgets.QPushButton(self.centralwidget)
        self.seeContainerInventory.setGeometry(QtCore.QRect(232, 238, 181, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.seeContainerInventory.setFont(font)
        self.seeContainerInventory.setObjectName("seeContainerInventory")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(202, 248, 31, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(412, 248, 16, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(428, 230, 331, 131))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(202, 318, 31, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.seeContainerHotGood = QtWidgets.QPushButton(self.centralwidget)
        self.seeContainerHotGood.setGeometry(QtCore.QRect(232, 308, 181, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.seeContainerHotGood.setFont(font)
        self.seeContainerHotGood.setObjectName("seeContainerHotGood")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(412, 318, 16, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(190, 258, 20, 71))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(180, 278, 21, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(430, 370, 331, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(233, 338, 20, 151))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 450, 61, 31))
        font = QtGui.QFont()
        font.setFamily("新蒂下午茶体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(240, 480, 191, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(30, 30, 126, 123))
        self.graphicsView_2.setObjectName("graphicsView_2")
        stock_ui_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(stock_ui_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        stock_ui_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(stock_ui_window)
        self.statusbar.setObjectName("statusbar")
        stock_ui_window.setStatusBar(self.statusbar)

        self.retranslateUi(stock_ui_window)
        QtCore.QMetaObject.connectSlotsByName(stock_ui_window)

    def retranslateUi(self, stock_ui_window):
        _translate = QtCore.QCoreApplication.translate
        stock_ui_window.setWindowTitle(_translate("stock_ui_window", "采购员子界面"))
        self.label.setText(_translate("stock_ui_window", "欢迎采购员"))
        self.comboBox.setItemText(0, _translate("stock_ui_window", "(请选择仓库)"))
        self.seeWareHouseInventory.setText(_translate("stock_ui_window", "查看仓库存量"))
        self.stock.setText(_translate("stock_ui_window", "采购"))
        self.addGood.setText(_translate("stock_ui_window", "添加商品"))
        self.comboBox_2.setItemText(0, _translate("stock_ui_window", "(请选择货柜)"))
        self.seeContainerInventory.setText(_translate("stock_ui_window", "查看货柜的商品存量"))
        self.seeContainerHotGood.setText(_translate("stock_ui_window", "查看货柜的热销商品"))
        self.label_2.setText(_translate("stock_ui_window", "可视化"))
